---
title: "Exploratory Analysis Script"
date: "2024-04-08"
output: html_document
---

# Setup

```{r}
#load needed packages. make sure they are installed.
library(here) #for data loading/saving
library(dplyr)
library(tidyverse)
```

Load the data.

```{r}
#Path to data. Note the use of the here() package and not absolute paths
data_location <- here::here("data","processed-data","processeddata.rds")
#load data
data <- readRDS(data_location)
```

# Data exploration through tables

```{r}
summary_data <- data %>%
  summarise(
    n_variety = n_distinct(variety),
    n_location = n_distinct(location),
    n_year = n_distinct(year)
  )
print(summary_data)

# save to file
summarytable_file = here("results", "tables", "summarytable.rds")
saveRDS(summary_data, file = summarytable_file)
```

# Data exploration through figures

```{r}
#checking the variables 
table(data$variety)
table(data$location)
table(data$watered)
hist(data$year)
hist(data$peanut_yield)

#plotting yield by varieties, in ascending order
p1 <- ggplot(data, aes(x = reorder(variety, peanut_yield, median, na.rm = TRUE),
               y = peanut_yield)) +
  geom_boxplot() +
  theme_bw() +
  labs(
    x="Peanut Varieties",
    y="Peanut Yield (lb/acre)"
  )+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
plot(p1)
eda_p1 = here("results", "figures","eda_p1.png")
ggsave(filename = eda_p1, plot=p1) 

#plotting yield by watered vs non-watered
p2 <- ggplot(data, aes(x = watered, y = peanut_yield)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("FALSE" = "Non-Irrigated",
                              "TRUE" = "Irrigated")) +
  labs(x = "Irrigation", y = "Peanut Yield (lb/acre)") +
  theme_bw()
plot(p2)

eda_p2 = here("results", "figures","eda_p2.png")
ggsave(filename = eda_p2, plot=p2) 

#plotting yield by location
p3 <- ggplot(data, aes(x = location, y = peanut_yield)) +
  geom_boxplot(outlier.alpha = 0.2) +
  labs(x = "Location", y = "Peanut Yield (lb/acre)") +
  theme_bw()
plot(p3)

eda_p3 = here("results", "figures","eda_p3.png")
ggsave(filename = eda_p3, plot=p3) 

#plotting yield across years by location
# all years you want shown on the x-axis
all_years <- 2013:2025

# plotting yield across years by location
p4_data <- data %>%
  group_by(location, year) %>%
  summarise(
    mean_yield = mean(peanut_yield, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  complete(location, year = all_years)

p4 <- ggplot(p4_data, aes(x = factor(year, levels = all_years),
                          y = mean_yield,
                          group = location)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ location) +
  labs(x = "Year", y = "Mean Peanut Yield (lb/acre)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot(p4)

eda_p4 = here("results", "figures","eda_p4.png")
ggsave(filename = eda_p4, plot=p4) 
```
