---
title: Project Review Template 
author: Marco Reina
date: 04/29/2026
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project:Statistical Analysis of Peanut Variety Performance in a State Variety Testing Program

Name of project author(s): Santiago Emil A. Joson IV

Name of project reviewer: Marco Reina


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

* Marco Reina: For the background, it feels like it require a bit more. Like maybe introduce the most popular cultivars and why people preferred them, and maybe mention why people would choose other type of cultivar. Do the farmer select it based on their own circumstances? price, access to genetics, resistance to drought (I am not a plant pathologist, so I understand if my ideas are not valid). Also, why variety identities were anonymized? It needs to be set up early in the paper.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* some contextualization and motivation

## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

* Marco Reina: Questions to adress are clear

### Summary assessment

* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

* Marco Reina: Sources are provided. Codebook is not provided. Table 1, please include a short sentence description of each one of the variables if all are presented. If not maybe just move the table to the supplement material. Probably table 1 would be better if only include the selected variables.

### Summary assessment

* source and overall structure of data somewhat explained

## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

* Marco Reina: data seems to be adequeate explored and prepocessed. I am just confused about the "-9" 

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component

## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

* Marco Reina: I am not sure if having different type of statistical analysis is recommended. I would stick with either ANOVA or t-test. In my opinion a Linear Model might be a better fit (because I am assuming different "n" per group). Followed by a post-hoc test, like Tukey HSD to determine the differences if the effect is significant. (Later I found out you did a Linear regression)

### Summary assessment

* defensible but not optimal analysis 

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

* Marco Reina: Field by variety seems to be a very busy figure, maybe it would translate better into a table. Then, in a table we can se the magnitud of the variance (either SE or SD). It would make the point even more visible about the high variance in some cultivars. The figures might require some polishing just to make it look "prettier", but there is nothing inheritly wrong with them.

### Summary assessment

* results are very well presented

## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

* Marco Reina: Discussion was not truly clear for me. It felt like reading the results again. Maybe add a few studies to contextualize these results with current research.

### Summary assessment
 
* minor parts wrong, missing or unclear

## Further comments

* Marco Reina:

- Are there ay subgroups within the cultivars? like is 014 related for example to 061? or are they all "just peanuts". If they are it would be interesting to group them by those subgroups. 

- Is the variance among the cultivars related or explained by any other variables? Do you have representatives for all the cultivars for irrigated and non-irrigated? Does the high variation in Midville is because the cultivars themselves have high variance?

- I know you counted for irrigation, but did you accounted for rain? was the irrigation in response of lack of rain, or the lack of irrigation the response to the availability of rain? I think "year" might be capturing that effect, as different year might have had different amounts of rain. If not it should be stated as a limitation.

- Additionally, I am not sure if we can claim "significance" if this dataset is observational rather than from a designed experiment.



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

* Marco Reina: There are some files that do not belong to the project like "height and weight distribution". Read me files need to be updated. I would suggest to have an qmd for the statistical-analysis.R

### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

* Marco Reina: A few more comments would be helpul

### Summary assessment

* decently documented with some gaps


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

* Marco Reina: Code was reproducible in eda.qmd and processingfile-v1.qmd; However, I was not able to run statistical-analysis.R due to my own computational limitations (my RAM is only 8GB) and I could not run the tuning grid.

### Summary assessment

* fully reproducible without issues 


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

* Marco Reina: I like that you compared the LM, LASSO, and RF. Could you please add the "predicted vs the actual" plots for the LM, LASSO, and RF

### Summary assessment

* decent level of thoroughness

## Further comments

* Marco Reina:

- Attapulgus does not seems to be a good group for comparison if only data from 2025 is available. Why to keep this?

- Table 4 is reporting a p-value of zero, is that correct?

- Table 5, I fee like both table 4 and 5 could have been analyzed using an LM, p-value is again reported as zero





