---
title: "Cleaning Script"
author: "Emil Joson"
date: "2026-04-08"
output: html_document
---


# Processing script

# Setup

# Package loading

Load needed packages. make sure they are installed.

```{r}
library(readxl) #for loading Excel files
library(dplyr) #for data processing/cleaning
library(tidyr) #for data processing/cleaning
library(skimr) #for nice visualization of data 
library(here) #to set paths
library(stringr) #for string processing
library(readr) #for data processing
library(ggplot2) #for visualization
library(gt) 

```

# Data loading

```{r}
# path to data
# note the use of the here() package and not absolute paths
data_location <- here::here("data","raw-data","peanuts.csv")
raw_data <- read.csv2(data_location, sep=",")
```

# Data checking

```{r}
str(raw_data)
skim(raw_data)
```


# Data cleaning

```{r}
#these are columns that should be numeric based on their names and data, but are currently classified as characters
num_cols <- c("plot_weight","total_seed_weight","calc_seed_weight_200",
              "seed_weight_200","seed_weight_100","seed_per_pound")

#convert "num stored as chr" columns into numeric
raw_data <- raw_data %>%
  mutate(across(all_of(num_cols), parse_number)) 

raw_data <- raw_data %>%
  # optional but helpful: trim whitespace so "   " becomes ""
  mutate(across(where(is.character), str_squish)) %>%
  # turn empty strings into NA
  mutate(across(where(is.character), ~ na_if(.x, ""))) %>%
  # turn "-9" strings into NA (only affects character columns)
  mutate(across(where(is.character), ~ na_if(.x, "-9"))) %>%
  # turn -9 numeric sentinel into NA (only affects numeric/integer columns)
  mutate(across(where(is.numeric), ~ na_if(.x, -9)))

#check missing data
colSums(is.na(raw_data))

#subset only variables needed
clean_data <- raw_data %>%
  select(year, location, watered, variety, peanut_yield)

#making a key for the variety names to be kept confidential
variety_key <- clean_data %>%
  distinct(variety) %>%              # get unique varieties
  arrange(variety) %>%               # optional: keeps numbering consistent
  mutate(variety_id = sprintf("%03d", row_number()))

#converting variety names with variety numbers
clean_data <- clean_data %>%
  left_join(variety_key, by = "variety") %>%
  select(-variety) %>%
  rename(variety = variety_id)

#only keeping entries that are present in all locations
variety_locations <- clean_data %>%
  group_by(variety) %>%
  summarise(n_locations = n_distinct(location))

valid_varieties <- variety_locations %>%
  filter(n_locations == 4) %>%
  pull(variety)

clean_data <- clean_data %>%
  filter(variety %in% valid_varieties)

#remove rows with missing yield
clean_data <- clean_data %>% 
  filter(!is.na(peanut_yield))

#checking final dataframe
clean_data %>%
  summarise(
    n_variety = n_distinct(variety),
    n_location = n_distinct(location),
    n_year = n_distinct(year)
  )

```

# Save data 

```{r}
save_data_location <- here::here("data","processed-data","processeddata.rds")
saveRDS(clean_data, file = save_data_location)

```



